<?php

namespace Database\Seeders;

use App\Models\product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            /* 1-15 */
            ['Áo sơ mi nam Aristino 1SSR14',  1470000.0,'product-1-1.png', 1, 5, 100, 1, 1, 'Hà Nội', 'Thiết kế: Áo sơ mi dài tay phom Slim Fit ôm nhẹ vừa vặn mà vẫn thoải mái vận động. Thiết kế tà lượn không túi, cùng màu xanh kẻ tinh tế mang đến phong cách thời thượng và lịch lãm cho các quý ông. Chất liệu: 50% Modal sợi sồi thiên nhiên mang đến bề mặt vải mềm mại, mịn màng, sự dễ chịu cho người mặc dù ở mùa nào trong năm. 50% Polyester giúp áo mỏng nhẹ, có độ trơn trượt, màu sắc nét và giữ màu tốt theo thời gian.', 1],
            ['ÁO SƠ MI NAM ARISTINO 1SS101S2',  1600000.0,'product-2-1.png', 1, 5, 100, 1, 1, 'Hà Nội', 'Thiết kế: Áo sơ mi dài tay phom Slim Fit ôm nhẹ vừa vặn mà vẫn thoải mái vận động. Thiết kế tà lượn không túi, cùng màu xanh kẻ tinh tế mang đến phong cách thời thượng và lịch lãm cho các quý ông. Chất liệu: 50% Modal sợi sồi thiên nhiên mang đến bề mặt vải mềm mại, mịn màng, sự dễ chịu cho người mặc dù ở mùa nào trong năm. 50% Polyester giúp áo mỏng nhẹ, có độ trơn trượt, màu sắc nét và giữ màu tốt theo thời gian.', 1],
            ['Áo sơ mi ngắn tay Aristino Boss ',  1200000.0,'product-3-1.png', 1, 5, 100, 1, 1, 'Hà Nội', 'Thiết kế: Áo sơ mi dài tay phom Slim Fit ôm nhẹ vừa vặn mà vẫn thoải mái vận động. Thiết kế tà lượn không túi, cùng màu xanh kẻ tinh tế mang đến phong cách thời thượng và lịch lãm cho các quý ông. Chất liệu: 50% Modal sợi sồi thiên nhiên mang đến bề mặt vải mềm mại, mịn màng, sự dễ chịu cho người mặc dù ở mùa nào trong năm. 50% Polyester giúp áo mỏng nhẹ, có độ trơn trượt, màu sắc nét và giữ màu tốt theo thời gian.', 1],
            ['Áo sơ mi dài tay Aristino ALS06302',  1470000.0,'product-4-1.png', 1, 5, 100, 1, 1, 'Hà Nội', 'Thiết kế: Áo sơ mi dài tay phom Slim Fit ôm nhẹ vừa vặn mà vẫn thoải mái vận động. Thiết kế tà lượn không túi, cùng màu xanh kẻ tinh tế mang đến phong cách thời thượng và lịch lãm cho các quý ông. Chất liệu: 50% Modal sợi sồi thiên nhiên mang đến bề mặt vải mềm mại, mịn màng, sự dễ chịu cho người mặc dù ở mùa nào trong năm. 50% Polyester giúp áo mỏng nhẹ, có độ trơn trượt, màu sắc nét và giữ màu tốt theo thời gian.', 1],
            ['Áo sơ mi kẻ dài tay Aristino',  995000.0,'product-5-1.png', 1, 3, 100, 1, 1, 'Hà Nội', 'Thiết kế: Áo sơ mi dài tay phom Slim Fit ôm nhẹ vừa vặn mà vẫn thoải mái vận động. Thiết kế tà lượn không túi, cùng màu xanh kẻ tinh tế mang đến phong cách thời thượng và lịch lãm cho các quý ông. Chất liệu: 50% Modal sợi sồi thiên nhiên mang đến bề mặt vải mềm mại, mịn màng, sự dễ chịu cho người mặc dù ở mùa nào trong năm. 50% Polyester giúp áo mỏng nhẹ, có độ trơn trượt, màu sắc nét và giữ màu tốt theo thời gian.', 1],
            ['Áo sơ mi ngắn tay nam Aristino ',  1470000.0,'product-6-1.png', 1, 5, 100, 1, 1, 'Hà Nội', 'Thiết kế: Áo sơ mi dài tay phom Slim Fit ôm nhẹ vừa vặn mà vẫn thoải mái vận động. Thiết kế tà lượn không túi, cùng màu xanh kẻ tinh tế mang đến phong cách thời thượng và lịch lãm cho các quý ông. Chất liệu: 50% Modal sợi sồi thiên nhiên mang đến bề mặt vải mềm mại, mịn màng, sự dễ chịu cho người mặc dù ở mùa nào trong năm. 50% Polyester giúp áo mỏng nhẹ, có độ trơn trượt, màu sắc nét và giữ màu tốt theo thời gian.', 1],
            ['Áo sơ mi nam dài tay Aristino màu Xanh kẻ nâu',  895000.0,'product-7-1.png', 1, 2, 100, 1, 1, 'Hà Nội', 'Thiết kế: Áo sơ mi dài tay phom Slim Fit ôm nhẹ vừa vặn mà vẫn thoải mái vận động. Thiết kế tà lượn không túi, cùng màu xanh kẻ tinh tế mang đến phong cách thời thượng và lịch lãm cho các quý ông. Chất liệu: 50% Modal sợi sồi thiên nhiên mang đến bề mặt vải mềm mại, mịn màng, sự dễ chịu cho người mặc dù ở mùa nào trong năm. 50% Polyester giúp áo mỏng nhẹ, có độ trơn trượt, màu sắc nét và giữ màu tốt theo thời gian.', 1],
            ['Áo sơ mi nam dài tay Aristino màu Xanh kẻ',  895000.0,'product-8-1.png', 1, 1, 100, 1, 1, 'Hà Nội', 'Thiết kế: Áo sơ mi dài tay phom Slim Fit ôm nhẹ vừa vặn mà vẫn thoải mái vận động. Thiết kế tà lượn không túi, cùng màu xanh kẻ tinh tế mang đến phong cách thời thượng và lịch lãm cho các quý ông. Chất liệu: 50% Modal sợi sồi thiên nhiên mang đến bề mặt vải mềm mại, mịn màng, sự dễ chịu cho người mặc dù ở mùa nào trong năm. 50% Polyester giúp áo mỏng nhẹ, có độ trơn trượt, màu sắc nét và giữ màu tốt theo thời gian.', 1],
            ['Áo sơ mi kẻ dài tay Aristino màu xanh tím than',  895000.0,'product-9-1.png', 1, 6, 100, 1, 1, 'Hà Nội', 'Thiết kế: Áo sơ mi dài tay phom Slim Fit ôm nhẹ vừa vặn mà vẫn thoải mái vận động. Thiết kế tà lượn không túi, cùng màu xanh kẻ tinh tế mang đến phong cách thời thượng và lịch lãm cho các quý ông. Chất liệu: 50% Modal sợi sồi thiên nhiên mang đến bề mặt vải mềm mại, mịn màng, sự dễ chịu cho người mặc dù ở mùa nào trong năm. 50% Polyester giúp áo mỏng nhẹ, có độ trơn trượt, màu sắc nét và giữ màu tốt theo thời gian.', 1],
            ['SƠ MI ADAM XANH HOA - SMC102',  750000.0,'product-10-1.png', 1, 5, 100, 1, 1, 'Hà Nội', 'Thiết kế: Áo sơ mi dài tay phom Slim Fit ôm nhẹ vừa vặn mà vẫn thoải mái vận động. Thiết kế tà lượn không túi, cùng màu xanh kẻ tinh tế mang đến phong cách thời thượng và lịch lãm cho các quý ông. Chất liệu: 50% Modal sợi sồi thiên nhiên mang đến bề mặt vải mềm mại, mịn màng, sự dễ chịu cho người mặc dù ở mùa nào trong năm. 50% Polyester giúp áo mỏng nhẹ, có độ trơn trượt, màu sắc nét và giữ màu tốt theo thời gian.', 1],
            ['SƠ MI ADAM ĐỎ KẺ - SMC101',  750000.0,'product-11-1.png', 1, 4, 100, 1, 1, 'Hà Nội', 'Thiết kế: Áo sơ mi dài tay phom Slim Fit ôm nhẹ vừa vặn mà vẫn thoải mái vận động. Thiết kế tà lượn không túi, cùng màu xanh kẻ tinh tế mang đến phong cách thời thượng và lịch lãm cho các quý ông. Chất liệu: 50% Modal sợi sồi thiên nhiên mang đến bề mặt vải mềm mại, mịn màng, sự dễ chịu cho người mặc dù ở mùa nào trong năm. 50% Polyester giúp áo mỏng nhẹ, có độ trơn trượt, màu sắc nét và giữ màu tốt theo thời gian.', 1],
            ['SƠ MI ADAM XANH BẠC HÀ KẺ ',  750000.0,'product-12-1.png', 1, 4, 100, 1, 1, 'Hà Nội', 'Thiết kế: Áo sơ mi dài tay phom Slim Fit ôm nhẹ vừa vặn mà vẫn thoải mái vận động. Thiết kế tà lượn không túi, cùng màu xanh kẻ tinh tế mang đến phong cách thời thượng và lịch lãm cho các quý ông. Chất liệu: 50% Modal sợi sồi thiên nhiên mang đến bề mặt vải mềm mại, mịn màng, sự dễ chịu cho người mặc dù ở mùa nào trong năm. 50% Polyester giúp áo mỏng nhẹ, có độ trơn trượt, màu sắc nét và giữ màu tốt theo thời gian.', 1],
            ['SƠ MI ADAM XANH KẺ SỌC - SMC099X',  750000.0,'product-13-1.png', 1, 4, 100, 1, 1, 'Hà Nội', 'Thiết kế: Áo sơ mi dài tay phom Slim Fit ôm nhẹ vừa vặn mà vẫn thoải mái vận động. Thiết kế tà lượn không túi, cùng màu xanh kẻ tinh tế mang đến phong cách thời thượng và lịch lãm cho các quý ông. Chất liệu: 50% Modal sợi sồi thiên nhiên mang đến bề mặt vải mềm mại, mịn màng, sự dễ chịu cho người mặc dù ở mùa nào trong năm. 50% Polyester giúp áo mỏng nhẹ, có độ trơn trượt, màu sắc nét và giữ màu tốt theo thời gian.', 1],
            ['SƠ MI ADAM GHI KẺ SỌC - SMC099G',  750000.0,'product-14-1.png', 1, 4, 100, 1, 1, 'Hà Nội', 'Thiết kế: Áo sơ mi dài tay phom Slim Fit ôm nhẹ vừa vặn mà vẫn thoải mái vận động. Thiết kế tà lượn không túi, cùng màu xanh kẻ tinh tế mang đến phong cách thời thượng và lịch lãm cho các quý ông. Chất liệu: 50% Modal sợi sồi thiên nhiên mang đến bề mặt vải mềm mại, mịn màng, sự dễ chịu cho người mặc dù ở mùa nào trong năm. 50% Polyester giúp áo mỏng nhẹ, có độ trơn trượt, màu sắc nét và giữ màu tốt theo thời gian.', 1],
            ['SƠ MI ADAM ĐEN HOA VÀNG - SMC098',  750000.0,'product-15-1.png', 1, 4, 100, 1, 1, 'Hà Nội', 'Thiết kế: Áo sơ mi dài tay phom Slim Fit ôm nhẹ vừa vặn mà vẫn thoải mái vận động. Thiết kế tà lượn không túi, cùng màu xanh kẻ tinh tế mang đến phong cách thời thượng và lịch lãm cho các quý ông. Chất liệu: 50% Modal sợi sồi thiên nhiên mang đến bề mặt vải mềm mại, mịn màng, sự dễ chịu cho người mặc dù ở mùa nào trong năm. 50% Polyester giúp áo mỏng nhẹ, có độ trơn trượt, màu sắc nét và giữ màu tốt theo thời gian.', 1],
            /* 16-30 */
            ['ÁO PHÔNG MONGTOGHI ĐEN KẺ SỌC TRẮNG',  500000.0,'product-16-1.png', 2, 4, 100, 1, 1, 'Hà Nội', 'Chất liệu: Len montoghi - ưu điểm mềm, nhẹ, thoáng mát, không gây kích ứng da trong quá trình sử dụng. Giúp thấm hút mồ hôi trong quá trình vận động và sinh hoạt hàng ngày. Form dáng: Regular fit - sản phẩm ôm vừa đủ giúp tôn body của người mặc. Hoạ tiết: Tone màu be với hoạ tiết kẻ sọc đen tạo điểm nhấn tổng thể. Với hoạ tiết này giúp cho người mặc trở nên nổi bật, hack chiều cao với những outfit đi kèm quần sáng màu như be, trắng. Có thể da dạng kết hợp cùng những item như jean, sneaker, giày tây, nón lưỡi trai...', 1],
            ['ÁO PHÔNG MONGTOGHI XANH KẺ TRẮNG',  550000.0,'product-17-1.png', 2, 4, 100, 1, 1, 'Hà Nội', 'Chất liệu: Len montoghi - ưu điểm mềm, nhẹ, thoáng mát, không gây kích ứng da trong quá trình sử dụng. Giúp thấm hút mồ hôi trong quá trình vận động và sinh hoạt hàng ngày. Form dáng: Regular fit - sản phẩm ôm vừa đủ giúp tôn body của người mặc. Hoạ tiết: Tone màu be với hoạ tiết kẻ sọc đen tạo điểm nhấn tổng thể. Với hoạ tiết này giúp cho người mặc trở nên nổi bật, hack chiều cao với những outfit đi kèm quần sáng màu như be, trắng. Có thể da dạng kết hợp cùng những item như jean, sneaker, giày tây, nón lưỡi trai...', 1],
            ['ÁO PHÔNG MONGTOGHI NÂU VIỀN CỔ TRẮNG',  550000.0,'product-18-1.png', 2, 5, 100, 1, 1, 'Hà Nội', 'Chất liệu: Len montoghi - ưu điểm mềm, nhẹ, thoáng mát, không gây kích ứng da trong quá trình sử dụng. Giúp thấm hút mồ hôi trong quá trình vận động và sinh hoạt hàng ngày. Form dáng: Regular fit - sản phẩm ôm vừa đủ giúp tôn body của người mặc. Hoạ tiết: Tone màu be với hoạ tiết kẻ sọc đen tạo điểm nhấn tổng thể. Với hoạ tiết này giúp cho người mặc trở nên nổi bật, hack chiều cao với những outfit đi kèm quần sáng màu như be, trắng. Có thể da dạng kết hợp cùng những item như jean, sneaker, giày tây, nón lưỡi trai...', 1],
            ['ÁO PHÔNG MONGTOGHI NÂU - AP085N',  550000.0,'product-19-1.png', 2, 5, 100, 1, 1, 'Hà Nội', 'Chất liệu: Len montoghi - ưu điểm mềm, nhẹ, thoáng mát, không gây kích ứng da trong quá trình sử dụng. Giúp thấm hút mồ hôi trong quá trình vận động và sinh hoạt hàng ngày. Form dáng: Regular fit - sản phẩm ôm vừa đủ giúp tôn body của người mặc. Hoạ tiết: Tone màu be với hoạ tiết kẻ sọc đen tạo điểm nhấn tổng thể. Với hoạ tiết này giúp cho người mặc trở nên nổi bật, hack chiều cao với những outfit đi kèm quần sáng màu như be, trắng. Có thể da dạng kết hợp cùng những item như jean, sneaker, giày tây, nón lưỡi trai...', 1],
            ['ÁO PHÔNG MONGTOGHI CAM SỌC XANH',  550000.0,'product-20-1.png', 2, 5, 100, 1, 1, 'Hà Nội', 'Chất liệu: Len montoghi - ưu điểm mềm, nhẹ, thoáng mát, không gây kích ứng da trong quá trình sử dụng. Giúp thấm hút mồ hôi trong quá trình vận động và sinh hoạt hàng ngày. Form dáng: Regular fit - sản phẩm ôm vừa đủ giúp tôn body của người mặc. Hoạ tiết: Tone màu be với hoạ tiết kẻ sọc đen tạo điểm nhấn tổng thể. Với hoạ tiết này giúp cho người mặc trở nên nổi bật, hack chiều cao với những outfit đi kèm quần sáng màu như be, trắng. Có thể da dạng kết hợp cùng những item như jean, sneaker, giày tây, nón lưỡi trai...', 1],
            ['ÁO PHÔNG MONGTOGHI XANH PASTEL',  550000.0,'product-21-1.png', 2, 4, 100, 1, 1, 'Hà Nội', 'Chất liệu: Len montoghi - ưu điểm mềm, nhẹ, thoáng mát, không gây kích ứng da trong quá trình sử dụng. Giúp thấm hút mồ hôi trong quá trình vận động và sinh hoạt hàng ngày. Form dáng: Regular fit - sản phẩm ôm vừa đủ giúp tôn body của người mặc. Hoạ tiết: Tone màu be với hoạ tiết kẻ sọc đen tạo điểm nhấn tổng thể. Với hoạ tiết này giúp cho người mặc trở nên nổi bật, hack chiều cao với những outfit đi kèm quần sáng màu như be, trắng. Có thể da dạng kết hợp cùng những item như jean, sneaker, giày tây, nón lưỡi trai...', 1],
            ['Áo polo nam Aristino APS194S2',  650000.0,'product-22-1.png', 2, 3, 100, 1, 1, 'Hà Nội', 'Chất liệu: Len montoghi - ưu điểm mềm, nhẹ, thoáng mát, không gây kích ứng da trong quá trình sử dụng. Giúp thấm hút mồ hôi trong quá trình vận động và sinh hoạt hàng ngày. Form dáng: Regular fit - sản phẩm ôm vừa đủ giúp tôn body của người mặc. Hoạ tiết: Tone màu be với hoạ tiết kẻ sọc đen tạo điểm nhấn tổng thể. Với hoạ tiết này giúp cho người mặc trở nên nổi bật, hack chiều cao với những outfit đi kèm quần sáng màu như be, trắng. Có thể da dạng kết hợp cùng những item như jean, sneaker, giày tây, nón lưỡi trai...', 1],
            ['Áo polo nam Aristino APS178S2',  650000.0,'product-23-1.png', 2, 4, 100, 1, 1, 'Hà Nội', 'Chất liệu: Len montoghi - ưu điểm mềm, nhẹ, thoáng mát, không gây kích ứng da trong quá trình sử dụng. Giúp thấm hút mồ hôi trong quá trình vận động và sinh hoạt hàng ngày. Form dáng: Regular fit - sản phẩm ôm vừa đủ giúp tôn body của người mặc. Hoạ tiết: Tone màu be với hoạ tiết kẻ sọc đen tạo điểm nhấn tổng thể. Với hoạ tiết này giúp cho người mặc trở nên nổi bật, hack chiều cao với những outfit đi kèm quần sáng màu như be, trắng. Có thể da dạng kết hợp cùng những item như jean, sneaker, giày tây, nón lưỡi trai...', 1],
            ['Áo polo nam Aristino Boss 1PS043S2',  650000.0,'product-24-1.png', 2, 4, 100, 1, 1, 'Hà Nội', 'Chất liệu: Len montoghi - ưu điểm mềm, nhẹ, thoáng mát, không gây kích ứng da trong quá trình sử dụng. Giúp thấm hút mồ hôi trong quá trình vận động và sinh hoạt hàng ngày. Form dáng: Regular fit - sản phẩm ôm vừa đủ giúp tôn body của người mặc. Hoạ tiết: Tone màu be với hoạ tiết kẻ sọc đen tạo điểm nhấn tổng thể. Với hoạ tiết này giúp cho người mặc trở nên nổi bật, hack chiều cao với những outfit đi kèm quần sáng màu như be, trắng. Có thể da dạng kết hợp cùng những item như jean, sneaker, giày tây, nón lưỡi trai...', 1],
            ['Áo polo nam Aristino APS200S2',  650000.0,'product-25-1.png', 2, 3, 100, 1, 1, 'Hà Nội', 'Chất liệu: Len montoghi - ưu điểm mềm, nhẹ, thoáng mát, không gây kích ứng da trong quá trình sử dụng. Giúp thấm hút mồ hôi trong quá trình vận động và sinh hoạt hàng ngày. Form dáng: Regular fit - sản phẩm ôm vừa đủ giúp tôn body của người mặc. Hoạ tiết: Tone màu be với hoạ tiết kẻ sọc đen tạo điểm nhấn tổng thể. Với hoạ tiết này giúp cho người mặc trở nên nổi bật, hack chiều cao với những outfit đi kèm quần sáng màu như be, trắng. Có thể da dạng kết hợp cùng những item như jean, sneaker, giày tây, nón lưỡi trai...', 1],
            ['Áo polo nam Aristino APS172S2',  600000.0,'product-26-1.png', 2, 2, 100, 1, 1, 'Hà Nội', 'Chất liệu: Len montoghi - ưu điểm mềm, nhẹ, thoáng mát, không gây kích ứng da trong quá trình sử dụng. Giúp thấm hút mồ hôi trong quá trình vận động và sinh hoạt hàng ngày. Form dáng: Regular fit - sản phẩm ôm vừa đủ giúp tôn body của người mặc. Hoạ tiết: Tone màu be với hoạ tiết kẻ sọc đen tạo điểm nhấn tổng thể. Với hoạ tiết này giúp cho người mặc trở nên nổi bật, hack chiều cao với những outfit đi kèm quần sáng màu như be, trắng. Có thể da dạng kết hợp cùng những item như jean, sneaker, giày tây, nón lưỡi trai...', 1],
            ['Áo polo nam Aristino APS140S2',  750000.0,'product-27-1.png', 2, 5, 100, 1, 1, 'Hà Nội', 'Chất liệu: Len montoghi - ưu điểm mềm, nhẹ, thoáng mát, không gây kích ứng da trong quá trình sử dụng. Giúp thấm hút mồ hôi trong quá trình vận động và sinh hoạt hàng ngày. Form dáng: Regular fit - sản phẩm ôm vừa đủ giúp tôn body của người mặc. Hoạ tiết: Tone màu be với hoạ tiết kẻ sọc đen tạo điểm nhấn tổng thể. Với hoạ tiết này giúp cho người mặc trở nên nổi bật, hack chiều cao với những outfit đi kèm quần sáng màu như be, trắng. Có thể da dạng kết hợp cùng những item như jean, sneaker, giày tây, nón lưỡi trai...', 1],
            ['Áo polo nam Aristino APS134S2',  650000.0,'product-28-1.png', 2, 1, 100, 1, 1, 'Hà Nội', 'Chất liệu: Len montoghi - ưu điểm mềm, nhẹ, thoáng mát, không gây kích ứng da trong quá trình sử dụng. Giúp thấm hút mồ hôi trong quá trình vận động và sinh hoạt hàng ngày. Form dáng: Regular fit - sản phẩm ôm vừa đủ giúp tôn body của người mặc. Hoạ tiết: Tone màu be với hoạ tiết kẻ sọc đen tạo điểm nhấn tổng thể. Với hoạ tiết này giúp cho người mặc trở nên nổi bật, hack chiều cao với những outfit đi kèm quần sáng màu như be, trắng. Có thể da dạng kết hợp cùng những item như jean, sneaker, giày tây, nón lưỡi trai...', 1],
            ['Áo polo nam Aristino APS120S2',  525000.0,'product-29-1.png', 2, 1, 100, 1, 1, 'Hà Nội', 'Chất liệu: Len montoghi - ưu điểm mềm, nhẹ, thoáng mát, không gây kích ứng da trong quá trình sử dụng. Giúp thấm hút mồ hôi trong quá trình vận động và sinh hoạt hàng ngày. Form dáng: Regular fit - sản phẩm ôm vừa đủ giúp tôn body của người mặc. Hoạ tiết: Tone màu be với hoạ tiết kẻ sọc đen tạo điểm nhấn tổng thể. Với hoạ tiết này giúp cho người mặc trở nên nổi bật, hack chiều cao với những outfit đi kèm quần sáng màu như be, trắng. Có thể da dạng kết hợp cùng những item như jean, sneaker, giày tây, nón lưỡi trai...', 1],
            ['Áo polo nam Aristino APS201S2',  695000.0,'product-30-1.png', 2, 1, 100, 1, 1, 'Hà Nội', 'Chất liệu: Len montoghi - ưu điểm mềm, nhẹ, thoáng mát, không gây kích ứng da trong quá trình sử dụng. Giúp thấm hút mồ hôi trong quá trình vận động và sinh hoạt hàng ngày. Form dáng: Regular fit - sản phẩm ôm vừa đủ giúp tôn body của người mặc. Hoạ tiết: Tone màu be với hoạ tiết kẻ sọc đen tạo điểm nhấn tổng thể. Với hoạ tiết này giúp cho người mặc trở nên nổi bật, hack chiều cao với những outfit đi kèm quần sáng màu như be, trắng. Có thể da dạng kết hợp cùng những item như jean, sneaker, giày tây, nón lưỡi trai...', 1],
            /* 31-45 */
            ['ÁO POLO TRẮNG HỌA TIẾT NGỰC',  650000.0,'product-31.png', 3, 1, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Tech Golf. Thiết kế: Áo polo dài tay phom dáng Tech Golf được tinh chỉnh các thông số đem lại sự thoải mái tối đa theo từng cử động của golfer. Áo được nâng cấp tính năng Anti UV, giúp bảo vệ làn da với chỉ số kháng tia UV lên tới 98% và bền bỉ trong suốt thời gian sử dụng. Công nghệ sợi vải Moisture Wicking giúp áo thấm hút tốt, đồng thời khô nhanh hơn. Thiết kế khỏe khoắn, màu sắc nam tính, cùng họa tiết đại bàng độc đáo, sáng tạo trên ngực trái áo đem đến diện mạo trẻ trung và lịch lãm cho người mặc. Chất liệu: 77% Nylon cho bề mặt vải độ mịn mượt, mỏng nhẹ, 23% Spandex tạo độ co giãn tốt, thoải mái tối đa khi mặc.', 1],
            ['ÁO POLO ĐỎ VIỀN XANH - AP108',  650000.0,'product-32.png', 3, 1, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Tech Golf. Thiết kế: Áo polo dài tay phom dáng Tech Golf được tinh chỉnh các thông số đem lại sự thoải mái tối đa theo từng cử động của golfer. Áo được nâng cấp tính năng Anti UV, giúp bảo vệ làn da với chỉ số kháng tia UV lên tới 98% và bền bỉ trong suốt thời gian sử dụng. Công nghệ sợi vải Moisture Wicking giúp áo thấm hút tốt, đồng thời khô nhanh hơn. Thiết kế khỏe khoắn, màu sắc nam tính, cùng họa tiết đại bàng độc đáo, sáng tạo trên ngực trái áo đem đến diện mạo trẻ trung và lịch lãm cho người mặc. Chất liệu: 77% Nylon cho bề mặt vải độ mịn mượt, mỏng nhẹ, 23% Spandex tạo độ co giãn tốt, thoải mái tối đa khi mặc.', 1],
            ['ÁO POLO GHI THIẾT KẾ LÁ CỔ ĐEN KẺ',  650000.0,'product-33.png', 3, 5, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Tech Golf. Thiết kế: Áo polo dài tay phom dáng Tech Golf được tinh chỉnh các thông số đem lại sự thoải mái tối đa theo từng cử động của golfer. Áo được nâng cấp tính năng Anti UV, giúp bảo vệ làn da với chỉ số kháng tia UV lên tới 98% và bền bỉ trong suốt thời gian sử dụng. Công nghệ sợi vải Moisture Wicking giúp áo thấm hút tốt, đồng thời khô nhanh hơn. Thiết kế khỏe khoắn, màu sắc nam tính, cùng họa tiết đại bàng độc đáo, sáng tạo trên ngực trái áo đem đến diện mạo trẻ trung và lịch lãm cho người mặc. Chất liệu: 77% Nylon cho bề mặt vải độ mịn mượt, mỏng nhẹ, 23% Spandex tạo độ co giãn tốt, thoải mái tối đa khi mặc.', 1],
            ['ÁO POLO ĐEN THIẾT KẾ LÁ CỔ GHI KẺ',  650000.0,'product-34.png', 3, 5, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Tech Golf. Thiết kế: Áo polo dài tay phom dáng Tech Golf được tinh chỉnh các thông số đem lại sự thoải mái tối đa theo từng cử động của golfer. Áo được nâng cấp tính năng Anti UV, giúp bảo vệ làn da với chỉ số kháng tia UV lên tới 98% và bền bỉ trong suốt thời gian sử dụng. Công nghệ sợi vải Moisture Wicking giúp áo thấm hút tốt, đồng thời khô nhanh hơn. Thiết kế khỏe khoắn, màu sắc nam tính, cùng họa tiết đại bàng độc đáo, sáng tạo trên ngực trái áo đem đến diện mạo trẻ trung và lịch lãm cho người mặc. Chất liệu: 77% Nylon cho bề mặt vải độ mịn mượt, mỏng nhẹ, 23% Spandex tạo độ co giãn tốt, thoải mái tối đa khi mặc.', 1],
            ['ÁO POLO TRẮNG PHA CỔ KẺ XANH ĐỎ',  650000.0,'product-35.png', 3, 4, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Tech Golf. Thiết kế: Áo polo dài tay phom dáng Tech Golf được tinh chỉnh các thông số đem lại sự thoải mái tối đa theo từng cử động của golfer. Áo được nâng cấp tính năng Anti UV, giúp bảo vệ làn da với chỉ số kháng tia UV lên tới 98% và bền bỉ trong suốt thời gian sử dụng. Công nghệ sợi vải Moisture Wicking giúp áo thấm hút tốt, đồng thời khô nhanh hơn. Thiết kế khỏe khoắn, màu sắc nam tính, cùng họa tiết đại bàng độc đáo, sáng tạo trên ngực trái áo đem đến diện mạo trẻ trung và lịch lãm cho người mặc. Chất liệu: 77% Nylon cho bề mặt vải độ mịn mượt, mỏng nhẹ, 23% Spandex tạo độ co giãn tốt, thoải mái tối đa khi mặc.', 1],
            ['ÁO POLO TRẮNG FULL LOGO - AP105T',  650000.0,'product-36.png', 3, 3, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Tech Golf. Thiết kế: Áo polo dài tay phom dáng Tech Golf được tinh chỉnh các thông số đem lại sự thoải mái tối đa theo từng cử động của golfer. Áo được nâng cấp tính năng Anti UV, giúp bảo vệ làn da với chỉ số kháng tia UV lên tới 98% và bền bỉ trong suốt thời gian sử dụng. Công nghệ sợi vải Moisture Wicking giúp áo thấm hút tốt, đồng thời khô nhanh hơn. Thiết kế khỏe khoắn, màu sắc nam tính, cùng họa tiết đại bàng độc đáo, sáng tạo trên ngực trái áo đem đến diện mạo trẻ trung và lịch lãm cho người mặc. Chất liệu: 77% Nylon cho bề mặt vải độ mịn mượt, mỏng nhẹ, 23% Spandex tạo độ co giãn tốt, thoải mái tối đa khi mặc.', 1],
            ['ÁO POLO ĐEN MIX TRẮNG - AP104',  650000.0,'product-37.png', 3, 5, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Tech Golf. Thiết kế: Áo polo dài tay phom dáng Tech Golf được tinh chỉnh các thông số đem lại sự thoải mái tối đa theo từng cử động của golfer. Áo được nâng cấp tính năng Anti UV, giúp bảo vệ làn da với chỉ số kháng tia UV lên tới 98% và bền bỉ trong suốt thời gian sử dụng. Công nghệ sợi vải Moisture Wicking giúp áo thấm hút tốt, đồng thời khô nhanh hơn. Thiết kế khỏe khoắn, màu sắc nam tính, cùng họa tiết đại bàng độc đáo, sáng tạo trên ngực trái áo đem đến diện mạo trẻ trung và lịch lãm cho người mặc. Chất liệu: 77% Nylon cho bề mặt vải độ mịn mượt, mỏng nhẹ, 23% Spandex tạo độ co giãn tốt, thoải mái tối đa khi mặc.', 1],
            ['ÁO POLO XANH TÍM THAN KẺ BE TRẮNG',  650000.0,'product-38.png', 3, 5, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Tech Golf. Thiết kế: Áo polo dài tay phom dáng Tech Golf được tinh chỉnh các thông số đem lại sự thoải mái tối đa theo từng cử động của golfer. Áo được nâng cấp tính năng Anti UV, giúp bảo vệ làn da với chỉ số kháng tia UV lên tới 98% và bền bỉ trong suốt thời gian sử dụng. Công nghệ sợi vải Moisture Wicking giúp áo thấm hút tốt, đồng thời khô nhanh hơn. Thiết kế khỏe khoắn, màu sắc nam tính, cùng họa tiết đại bàng độc đáo, sáng tạo trên ngực trái áo đem đến diện mạo trẻ trung và lịch lãm cho người mặc. Chất liệu: 77% Nylon cho bề mặt vải độ mịn mượt, mỏng nhẹ, 23% Spandex tạo độ co giãn tốt, thoải mái tối đa khi mặc.', 1],
            ['ÁO POLO TRẮNG KẺ ĐỎ ĐEN - AP103T',  650000.0,'product-39.png', 3, 5, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Tech Golf. Thiết kế: Áo polo dài tay phom dáng Tech Golf được tinh chỉnh các thông số đem lại sự thoải mái tối đa theo từng cử động của golfer. Áo được nâng cấp tính năng Anti UV, giúp bảo vệ làn da với chỉ số kháng tia UV lên tới 98% và bền bỉ trong suốt thời gian sử dụng. Công nghệ sợi vải Moisture Wicking giúp áo thấm hút tốt, đồng thời khô nhanh hơn. Thiết kế khỏe khoắn, màu sắc nam tính, cùng họa tiết đại bàng độc đáo, sáng tạo trên ngực trái áo đem đến diện mạo trẻ trung và lịch lãm cho người mặc. Chất liệu: 77% Nylon cho bề mặt vải độ mịn mượt, mỏng nhẹ, 23% Spandex tạo độ co giãn tốt, thoải mái tối đa khi mặc.', 1],
            ['ÁO POLO ĐEN MIX VIỀN TRẮNG - AP102D',  650000.0,'product-40.png', 3, 5, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Tech Golf. Thiết kế: Áo polo dài tay phom dáng Tech Golf được tinh chỉnh các thông số đem lại sự thoải mái tối đa theo từng cử động của golfer. Áo được nâng cấp tính năng Anti UV, giúp bảo vệ làn da với chỉ số kháng tia UV lên tới 98% và bền bỉ trong suốt thời gian sử dụng. Công nghệ sợi vải Moisture Wicking giúp áo thấm hút tốt, đồng thời khô nhanh hơn. Thiết kế khỏe khoắn, màu sắc nam tính, cùng họa tiết đại bàng độc đáo, sáng tạo trên ngực trái áo đem đến diện mạo trẻ trung và lịch lãm cho người mặc. Chất liệu: 77% Nylon cho bề mặt vải độ mịn mượt, mỏng nhẹ, 23% Spandex tạo độ co giãn tốt, thoải mái tối đa khi mặc.', 1],
            ['ÁO POLO SPORTY TRẮNG - AP101',  650000.0,'product-41.png', 3, 2, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Tech Golf. Thiết kế: Áo polo dài tay phom dáng Tech Golf được tinh chỉnh các thông số đem lại sự thoải mái tối đa theo từng cử động của golfer. Áo được nâng cấp tính năng Anti UV, giúp bảo vệ làn da với chỉ số kháng tia UV lên tới 98% và bền bỉ trong suốt thời gian sử dụng. Công nghệ sợi vải Moisture Wicking giúp áo thấm hút tốt, đồng thời khô nhanh hơn. Thiết kế khỏe khoắn, màu sắc nam tính, cùng họa tiết đại bàng độc đáo, sáng tạo trên ngực trái áo đem đến diện mạo trẻ trung và lịch lãm cho người mặc. Chất liệu: 77% Nylon cho bề mặt vải độ mịn mượt, mỏng nhẹ, 23% Spandex tạo độ co giãn tốt, thoải mái tối đa khi mặc.', 1],
            ['ÁO POLO ĐEN KẺ ĐỎ TRẮNG - AP100D',  650000.0,'product-42.png', 3, 3, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Tech Golf. Thiết kế: Áo polo dài tay phom dáng Tech Golf được tinh chỉnh các thông số đem lại sự thoải mái tối đa theo từng cử động của golfer. Áo được nâng cấp tính năng Anti UV, giúp bảo vệ làn da với chỉ số kháng tia UV lên tới 98% và bền bỉ trong suốt thời gian sử dụng. Công nghệ sợi vải Moisture Wicking giúp áo thấm hút tốt, đồng thời khô nhanh hơn. Thiết kế khỏe khoắn, màu sắc nam tính, cùng họa tiết đại bàng độc đáo, sáng tạo trên ngực trái áo đem đến diện mạo trẻ trung và lịch lãm cho người mặc. Chất liệu: 77% Nylon cho bề mặt vải độ mịn mượt, mỏng nhẹ, 23% Spandex tạo độ co giãn tốt, thoải mái tối đa khi mặc.', 1],
            ['ÁO POLO ĐEN HỌA TIẾT NGỰC - AP099',  650000.0,'product-43.png', 3, 4, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Tech Golf. Thiết kế: Áo polo dài tay phom dáng Tech Golf được tinh chỉnh các thông số đem lại sự thoải mái tối đa theo từng cử động của golfer. Áo được nâng cấp tính năng Anti UV, giúp bảo vệ làn da với chỉ số kháng tia UV lên tới 98% và bền bỉ trong suốt thời gian sử dụng. Công nghệ sợi vải Moisture Wicking giúp áo thấm hút tốt, đồng thời khô nhanh hơn. Thiết kế khỏe khoắn, màu sắc nam tính, cùng họa tiết đại bàng độc đáo, sáng tạo trên ngực trái áo đem đến diện mạo trẻ trung và lịch lãm cho người mặc. Chất liệu: 77% Nylon cho bề mặt vải độ mịn mượt, mỏng nhẹ, 23% Spandex tạo độ co giãn tốt, thoải mái tối đa khi mặc.', 1],
            ['ÁO POLO ĐEN LOGO - AP097D',  650000.0,'product-44.png', 3, 5, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Tech Golf. Thiết kế: Áo polo dài tay phom dáng Tech Golf được tinh chỉnh các thông số đem lại sự thoải mái tối đa theo từng cử động của golfer. Áo được nâng cấp tính năng Anti UV, giúp bảo vệ làn da với chỉ số kháng tia UV lên tới 98% và bền bỉ trong suốt thời gian sử dụng. Công nghệ sợi vải Moisture Wicking giúp áo thấm hút tốt, đồng thời khô nhanh hơn. Thiết kế khỏe khoắn, màu sắc nam tính, cùng họa tiết đại bàng độc đáo, sáng tạo trên ngực trái áo đem đến diện mạo trẻ trung và lịch lãm cho người mặc. Chất liệu: 77% Nylon cho bề mặt vải độ mịn mượt, mỏng nhẹ, 23% Spandex tạo độ co giãn tốt, thoải mái tối đa khi mặc.', 1],
            ['ÁO POLO ĐEN THIẾT KẾ VIỀN CỔ - AP098D',  650000.0,'product-45.png', 3, 5, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Tech Golf. Thiết kế: Áo polo dài tay phom dáng Tech Golf được tinh chỉnh các thông số đem lại sự thoải mái tối đa theo từng cử động của golfer. Áo được nâng cấp tính năng Anti UV, giúp bảo vệ làn da với chỉ số kháng tia UV lên tới 98% và bền bỉ trong suốt thời gian sử dụng. Công nghệ sợi vải Moisture Wicking giúp áo thấm hút tốt, đồng thời khô nhanh hơn. Thiết kế khỏe khoắn, màu sắc nam tính, cùng họa tiết đại bàng độc đáo, sáng tạo trên ngực trái áo đem đến diện mạo trẻ trung và lịch lãm cho người mặc. Chất liệu: 77% Nylon cho bề mặt vải độ mịn mượt, mỏng nhẹ, 23% Spandex tạo độ co giãn tốt, thoải mái tối đa khi mặc.', 1],
            /* 46-55 */
            ['ÁO VEST ADAM ĐEN 2 HÀNG KHUY HỌA TIẾT HERRINGBONE',  3250000.0,'product-46-1.png', 4, 1, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Slim fit, sang trọng cách tân dựa trên tỷ lệ hình thể người đàn ông Việt Nam giúp bộ đồ trông sang trọng nhưng vẫn giữ được sự trẻ trung và hạn chế khuyết điểm. Cấu trúc: 2 hàng khuy ve nhọn - Đây là mẫu Suits thể hiện sự sang trọng, sẽ được kết hợp với ve nhọn bởi bản rộng của ve nhọn với độ xiên lớn sẽ tạo độ sâu phần cổ và gương mặt người mặc. Không như những mẫu một hàng khuy, điểm cuối hai ve vest 2 khuy được cố định tại phần eo. Ta sẽ chỉ nhìn thấy toàn bộ của một bên ve áo. Cho nên chỉ kiểu ve nhọn mới đáp ứng được yêu cầu về diện tích, độ phẳng, giúp phần ngực của quý ông được tôn lên. Phần ngực áo sẽ thường được thiết kế với hai khuy giả, cho nên việc dùng ve nhọn là để nhằm tạo sự đối xứng phần mép ngoài ve áo. Kiểu dệt Twill là cách dệt sử dụng lần lượt 2 sợi vải ngang nằm dưới và sau đó là nằm trên 2 sợi vải dọc tạo nên một bề mặt các đường vân chéo đặc biệt. Loại vải vân chéo này dày và mềm mại, có khả năng chống nhăn khá tốt và dễ dàng là ủi. Giày phù hợp: Nâu nhạt/Đỏ burgundy/Đen Sơ mi phù hợp: Sơ mi trắng/đen/đỏ burgundy/Beige... Hoạ tiết Herringbone giúp tạo ra điểm nhấn cho bộ suits, khiến cho người mặc cảm thấy độ sâu hơn, bắt mắt hơn,  Đây cũng là yếu tố giúp cân bằng lại các chi tiết của tổng thể, cũng như là sự cân bằng cổ điển và hiện đại, mang tới vẻ đẹp tinh tế và ấn tượng nhất. Chất liệu vải được sử dụng 80% cotton và 20% poly giúp bộ Suit thoáng mát, thấm hút tốt và vẫn giữ phom, hạn chế nhăn nhàu.', 1],
            ['ÁO VEST GHI KẺ NÂU ĐEN HỌA TIẾT HERRINGBONE',  3100000.0,'product-47-1.png', 4, 1, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Slim fit, sang trọng cách tân dựa trên tỷ lệ hình thể người đàn ông Việt Nam giúp bộ đồ trông sang trọng nhưng vẫn giữ được sự trẻ trung và hạn chế khuyết điểm. Cấu trúc: 2 hàng khuy ve nhọn - Đây là mẫu Suits thể hiện sự sang trọng, sẽ được kết hợp với ve nhọn bởi bản rộng của ve nhọn với độ xiên lớn sẽ tạo độ sâu phần cổ và gương mặt người mặc. Không như những mẫu một hàng khuy, điểm cuối hai ve vest 2 khuy được cố định tại phần eo. Ta sẽ chỉ nhìn thấy toàn bộ của một bên ve áo. Cho nên chỉ kiểu ve nhọn mới đáp ứng được yêu cầu về diện tích, độ phẳng, giúp phần ngực của quý ông được tôn lên. Phần ngực áo sẽ thường được thiết kế với hai khuy giả, cho nên việc dùng ve nhọn là để nhằm tạo sự đối xứng phần mép ngoài ve áo. Kiểu dệt Twill là cách dệt sử dụng lần lượt 2 sợi vải ngang nằm dưới và sau đó là nằm trên 2 sợi vải dọc tạo nên một bề mặt các đường vân chéo đặc biệt. Loại vải vân chéo này dày và mềm mại, có khả năng chống nhăn khá tốt và dễ dàng là ủi. Giày phù hợp: Nâu nhạt/Đỏ burgundy/Đen Sơ mi phù hợp: Sơ mi trắng/đen/đỏ burgundy/Beige... Hoạ tiết Herringbone giúp tạo ra điểm nhấn cho bộ suits, khiến cho người mặc cảm thấy độ sâu hơn, bắt mắt hơn,  Đây cũng là yếu tố giúp cân bằng lại các chi tiết của tổng thể, cũng như là sự cân bằng cổ điển và hiện đại, mang tới vẻ đẹp tinh tế và ấn tượng nhất. Chất liệu vải được sử dụng 80% cotton và 20% poly giúp bộ Suit thoáng mát, thấm hút tốt và vẫn giữ phom, hạn chế nhăn nhàu.', 1],
            ['ÁO VEST ADAM XANH 2 HÀNG KHUY HỌA TIẾT HERRINGBONE',  3250000.0,'product-48-1.png', 4, 1, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Slim fit, sang trọng cách tân dựa trên tỷ lệ hình thể người đàn ông Việt Nam giúp bộ đồ trông sang trọng nhưng vẫn giữ được sự trẻ trung và hạn chế khuyết điểm. Cấu trúc: 2 hàng khuy ve nhọn - Đây là mẫu Suits thể hiện sự sang trọng, sẽ được kết hợp với ve nhọn bởi bản rộng của ve nhọn với độ xiên lớn sẽ tạo độ sâu phần cổ và gương mặt người mặc. Không như những mẫu một hàng khuy, điểm cuối hai ve vest 2 khuy được cố định tại phần eo. Ta sẽ chỉ nhìn thấy toàn bộ của một bên ve áo. Cho nên chỉ kiểu ve nhọn mới đáp ứng được yêu cầu về diện tích, độ phẳng, giúp phần ngực của quý ông được tôn lên. Phần ngực áo sẽ thường được thiết kế với hai khuy giả, cho nên việc dùng ve nhọn là để nhằm tạo sự đối xứng phần mép ngoài ve áo. Kiểu dệt Twill là cách dệt sử dụng lần lượt 2 sợi vải ngang nằm dưới và sau đó là nằm trên 2 sợi vải dọc tạo nên một bề mặt các đường vân chéo đặc biệt. Loại vải vân chéo này dày và mềm mại, có khả năng chống nhăn khá tốt và dễ dàng là ủi. Giày phù hợp: Nâu nhạt/Đỏ burgundy/Đen Sơ mi phù hợp: Sơ mi trắng/đen/đỏ burgundy/Beige... Hoạ tiết Herringbone giúp tạo ra điểm nhấn cho bộ suits, khiến cho người mặc cảm thấy độ sâu hơn, bắt mắt hơn,  Đây cũng là yếu tố giúp cân bằng lại các chi tiết của tổng thể, cũng như là sự cân bằng cổ điển và hiện đại, mang tới vẻ đẹp tinh tế và ấn tượng nhất. Chất liệu vải được sử dụng 80% cotton và 20% poly giúp bộ Suit thoáng mát, thấm hút tốt và vẫn giữ phom, hạn chế nhăn nhàu.', 1],
            ['ÁO VEST XANH KẺ Ô TRẮNG HỌA TIẾT HERRINGBONE',  3100000.0,'product-49-1.png', 4, 1, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Slim fit, sang trọng cách tân dựa trên tỷ lệ hình thể người đàn ông Việt Nam giúp bộ đồ trông sang trọng nhưng vẫn giữ được sự trẻ trung và hạn chế khuyết điểm. Cấu trúc: 2 hàng khuy ve nhọn - Đây là mẫu Suits thể hiện sự sang trọng, sẽ được kết hợp với ve nhọn bởi bản rộng của ve nhọn với độ xiên lớn sẽ tạo độ sâu phần cổ và gương mặt người mặc. Không như những mẫu một hàng khuy, điểm cuối hai ve vest 2 khuy được cố định tại phần eo. Ta sẽ chỉ nhìn thấy toàn bộ của một bên ve áo. Cho nên chỉ kiểu ve nhọn mới đáp ứng được yêu cầu về diện tích, độ phẳng, giúp phần ngực của quý ông được tôn lên. Phần ngực áo sẽ thường được thiết kế với hai khuy giả, cho nên việc dùng ve nhọn là để nhằm tạo sự đối xứng phần mép ngoài ve áo. Kiểu dệt Twill là cách dệt sử dụng lần lượt 2 sợi vải ngang nằm dưới và sau đó là nằm trên 2 sợi vải dọc tạo nên một bề mặt các đường vân chéo đặc biệt. Loại vải vân chéo này dày và mềm mại, có khả năng chống nhăn khá tốt và dễ dàng là ủi. Giày phù hợp: Nâu nhạt/Đỏ burgundy/Đen Sơ mi phù hợp: Sơ mi trắng/đen/đỏ burgundy/Beige... Hoạ tiết Herringbone giúp tạo ra điểm nhấn cho bộ suits, khiến cho người mặc cảm thấy độ sâu hơn, bắt mắt hơn,  Đây cũng là yếu tố giúp cân bằng lại các chi tiết của tổng thể, cũng như là sự cân bằng cổ điển và hiện đại, mang tới vẻ đẹp tinh tế và ấn tượng nhất. Chất liệu vải được sử dụng 80% cotton và 20% poly giúp bộ Suit thoáng mát, thấm hút tốt và vẫn giữ phom, hạn chế nhăn nhàu.', 1],
            ['ÁO VEST ADAM BEIGE SỮA HỌA TIẾT HERRINGBONE',  2750000.0,'product-50-1.png', 4, 1, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Slim fit, sang trọng cách tân dựa trên tỷ lệ hình thể người đàn ông Việt Nam giúp bộ đồ trông sang trọng nhưng vẫn giữ được sự trẻ trung và hạn chế khuyết điểm. Cấu trúc: 2 hàng khuy ve nhọn - Đây là mẫu Suits thể hiện sự sang trọng, sẽ được kết hợp với ve nhọn bởi bản rộng của ve nhọn với độ xiên lớn sẽ tạo độ sâu phần cổ và gương mặt người mặc. Không như những mẫu một hàng khuy, điểm cuối hai ve vest 2 khuy được cố định tại phần eo. Ta sẽ chỉ nhìn thấy toàn bộ của một bên ve áo. Cho nên chỉ kiểu ve nhọn mới đáp ứng được yêu cầu về diện tích, độ phẳng, giúp phần ngực của quý ông được tôn lên. Phần ngực áo sẽ thường được thiết kế với hai khuy giả, cho nên việc dùng ve nhọn là để nhằm tạo sự đối xứng phần mép ngoài ve áo. Kiểu dệt Twill là cách dệt sử dụng lần lượt 2 sợi vải ngang nằm dưới và sau đó là nằm trên 2 sợi vải dọc tạo nên một bề mặt các đường vân chéo đặc biệt. Loại vải vân chéo này dày và mềm mại, có khả năng chống nhăn khá tốt và dễ dàng là ủi. Giày phù hợp: Nâu nhạt/Đỏ burgundy/Đen Sơ mi phù hợp: Sơ mi trắng/đen/đỏ burgundy/Beige... Hoạ tiết Herringbone giúp tạo ra điểm nhấn cho bộ suits, khiến cho người mặc cảm thấy độ sâu hơn, bắt mắt hơn,  Đây cũng là yếu tố giúp cân bằng lại các chi tiết của tổng thể, cũng như là sự cân bằng cổ điển và hiện đại, mang tới vẻ đẹp tinh tế và ấn tượng nhất. Chất liệu vải được sử dụng 80% cotton và 20% poly giúp bộ Suit thoáng mát, thấm hút tốt và vẫn giữ phom, hạn chế nhăn nhàu.', 1],
            ['ÁO VEST GHI SÁNG TRƠN HỌA TIẾT HERRINGBONE',  3550000.0,'product-51-1.png', 4, 1, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Slim fit, sang trọng cách tân dựa trên tỷ lệ hình thể người đàn ông Việt Nam giúp bộ đồ trông sang trọng nhưng vẫn giữ được sự trẻ trung và hạn chế khuyết điểm. Cấu trúc: 2 hàng khuy ve nhọn - Đây là mẫu Suits thể hiện sự sang trọng, sẽ được kết hợp với ve nhọn bởi bản rộng của ve nhọn với độ xiên lớn sẽ tạo độ sâu phần cổ và gương mặt người mặc. Không như những mẫu một hàng khuy, điểm cuối hai ve vest 2 khuy được cố định tại phần eo. Ta sẽ chỉ nhìn thấy toàn bộ của một bên ve áo. Cho nên chỉ kiểu ve nhọn mới đáp ứng được yêu cầu về diện tích, độ phẳng, giúp phần ngực của quý ông được tôn lên. Phần ngực áo sẽ thường được thiết kế với hai khuy giả, cho nên việc dùng ve nhọn là để nhằm tạo sự đối xứng phần mép ngoài ve áo. Kiểu dệt Twill là cách dệt sử dụng lần lượt 2 sợi vải ngang nằm dưới và sau đó là nằm trên 2 sợi vải dọc tạo nên một bề mặt các đường vân chéo đặc biệt. Loại vải vân chéo này dày và mềm mại, có khả năng chống nhăn khá tốt và dễ dàng là ủi. Giày phù hợp: Nâu nhạt/Đỏ burgundy/Đen Sơ mi phù hợp: Sơ mi trắng/đen/đỏ burgundy/Beige... Hoạ tiết Herringbone giúp tạo ra điểm nhấn cho bộ suits, khiến cho người mặc cảm thấy độ sâu hơn, bắt mắt hơn,  Đây cũng là yếu tố giúp cân bằng lại các chi tiết của tổng thể, cũng như là sự cân bằng cổ điển và hiện đại, mang tới vẻ đẹp tinh tế và ấn tượng nhất. Chất liệu vải được sử dụng 80% cotton và 20% poly giúp bộ Suit thoáng mát, thấm hút tốt và vẫn giữ phom, hạn chế nhăn nhàu.', 1],
            ['ÁO VEST ADAM XANH TÍM THAN KẺ Ô',  3200000.0,'product-52-1.png', 4, 1, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Slim fit, sang trọng cách tân dựa trên tỷ lệ hình thể người đàn ông Việt Nam giúp bộ đồ trông sang trọng nhưng vẫn giữ được sự trẻ trung và hạn chế khuyết điểm. Cấu trúc: 2 hàng khuy ve nhọn - Đây là mẫu Suits thể hiện sự sang trọng, sẽ được kết hợp với ve nhọn bởi bản rộng của ve nhọn với độ xiên lớn sẽ tạo độ sâu phần cổ và gương mặt người mặc. Không như những mẫu một hàng khuy, điểm cuối hai ve vest 2 khuy được cố định tại phần eo. Ta sẽ chỉ nhìn thấy toàn bộ của một bên ve áo. Cho nên chỉ kiểu ve nhọn mới đáp ứng được yêu cầu về diện tích, độ phẳng, giúp phần ngực của quý ông được tôn lên. Phần ngực áo sẽ thường được thiết kế với hai khuy giả, cho nên việc dùng ve nhọn là để nhằm tạo sự đối xứng phần mép ngoài ve áo. Kiểu dệt Twill là cách dệt sử dụng lần lượt 2 sợi vải ngang nằm dưới và sau đó là nằm trên 2 sợi vải dọc tạo nên một bề mặt các đường vân chéo đặc biệt. Loại vải vân chéo này dày và mềm mại, có khả năng chống nhăn khá tốt và dễ dàng là ủi. Giày phù hợp: Nâu nhạt/Đỏ burgundy/Đen Sơ mi phù hợp: Sơ mi trắng/đen/đỏ burgundy/Beige... Hoạ tiết Herringbone giúp tạo ra điểm nhấn cho bộ suits, khiến cho người mặc cảm thấy độ sâu hơn, bắt mắt hơn,  Đây cũng là yếu tố giúp cân bằng lại các chi tiết của tổng thể, cũng như là sự cân bằng cổ điển và hiện đại, mang tới vẻ đẹp tinh tế và ấn tượng nhất. Chất liệu vải được sử dụng 80% cotton và 20% poly giúp bộ Suit thoáng mát, thấm hút tốt và vẫn giữ phom, hạn chế nhăn nhàu.', 1],
            ['ÁO VEST ADAM HỌA TIẾT STRIPE',  2950000.0,'product-53-1.png', 4, 1, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Slim fit, sang trọng cách tân dựa trên tỷ lệ hình thể người đàn ông Việt Nam giúp bộ đồ trông sang trọng nhưng vẫn giữ được sự trẻ trung và hạn chế khuyết điểm. Cấu trúc: 2 hàng khuy ve nhọn - Đây là mẫu Suits thể hiện sự sang trọng, sẽ được kết hợp với ve nhọn bởi bản rộng của ve nhọn với độ xiên lớn sẽ tạo độ sâu phần cổ và gương mặt người mặc. Không như những mẫu một hàng khuy, điểm cuối hai ve vest 2 khuy được cố định tại phần eo. Ta sẽ chỉ nhìn thấy toàn bộ của một bên ve áo. Cho nên chỉ kiểu ve nhọn mới đáp ứng được yêu cầu về diện tích, độ phẳng, giúp phần ngực của quý ông được tôn lên. Phần ngực áo sẽ thường được thiết kế với hai khuy giả, cho nên việc dùng ve nhọn là để nhằm tạo sự đối xứng phần mép ngoài ve áo. Kiểu dệt Twill là cách dệt sử dụng lần lượt 2 sợi vải ngang nằm dưới và sau đó là nằm trên 2 sợi vải dọc tạo nên một bề mặt các đường vân chéo đặc biệt. Loại vải vân chéo này dày và mềm mại, có khả năng chống nhăn khá tốt và dễ dàng là ủi. Giày phù hợp: Nâu nhạt/Đỏ burgundy/Đen Sơ mi phù hợp: Sơ mi trắng/đen/đỏ burgundy/Beige... Hoạ tiết Herringbone giúp tạo ra điểm nhấn cho bộ suits, khiến cho người mặc cảm thấy độ sâu hơn, bắt mắt hơn,  Đây cũng là yếu tố giúp cân bằng lại các chi tiết của tổng thể, cũng như là sự cân bằng cổ điển và hiện đại, mang tới vẻ đẹp tinh tế và ấn tượng nhất. Chất liệu vải được sử dụng 80% cotton và 20% poly giúp bộ Suit thoáng mát, thấm hút tốt và vẫn giữ phom, hạn chế nhăn nhàu.', 1],
            ['ÁO VEST ADAM XANH SÁNG HỌA TIẾT STRIPE',  2950000.0,'product-54-1.png', 4, 1, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Slim fit, sang trọng cách tân dựa trên tỷ lệ hình thể người đàn ông Việt Nam giúp bộ đồ trông sang trọng nhưng vẫn giữ được sự trẻ trung và hạn chế khuyết điểm. Cấu trúc: 2 hàng khuy ve nhọn - Đây là mẫu Suits thể hiện sự sang trọng, sẽ được kết hợp với ve nhọn bởi bản rộng của ve nhọn với độ xiên lớn sẽ tạo độ sâu phần cổ và gương mặt người mặc. Không như những mẫu một hàng khuy, điểm cuối hai ve vest 2 khuy được cố định tại phần eo. Ta sẽ chỉ nhìn thấy toàn bộ của một bên ve áo. Cho nên chỉ kiểu ve nhọn mới đáp ứng được yêu cầu về diện tích, độ phẳng, giúp phần ngực của quý ông được tôn lên. Phần ngực áo sẽ thường được thiết kế với hai khuy giả, cho nên việc dùng ve nhọn là để nhằm tạo sự đối xứng phần mép ngoài ve áo. Kiểu dệt Twill là cách dệt sử dụng lần lượt 2 sợi vải ngang nằm dưới và sau đó là nằm trên 2 sợi vải dọc tạo nên một bề mặt các đường vân chéo đặc biệt. Loại vải vân chéo này dày và mềm mại, có khả năng chống nhăn khá tốt và dễ dàng là ủi. Giày phù hợp: Nâu nhạt/Đỏ burgundy/Đen Sơ mi phù hợp: Sơ mi trắng/đen/đỏ burgundy/Beige... Hoạ tiết Herringbone giúp tạo ra điểm nhấn cho bộ suits, khiến cho người mặc cảm thấy độ sâu hơn, bắt mắt hơn,  Đây cũng là yếu tố giúp cân bằng lại các chi tiết của tổng thể, cũng như là sự cân bằng cổ điển và hiện đại, mang tới vẻ đẹp tinh tế và ấn tượng nhất. Chất liệu vải được sử dụng 80% cotton và 20% poly giúp bộ Suit thoáng mát, thấm hút tốt và vẫn giữ phom, hạn chế nhăn nhàu.', 1],
            ['ÁO VEST ADAM ĐEN 2 KHUY HỌA TIẾT HERRINGBONE',  2950000.0,'product-55-1.png', 4, 1, 100, 1, 1, 'Hà Nội', 'Kiểu dáng: Slim fit, sang trọng cách tân dựa trên tỷ lệ hình thể người đàn ông Việt Nam giúp bộ đồ trông sang trọng nhưng vẫn giữ được sự trẻ trung và hạn chế khuyết điểm. Cấu trúc: 2 hàng khuy ve nhọn - Đây là mẫu Suits thể hiện sự sang trọng, sẽ được kết hợp với ve nhọn bởi bản rộng của ve nhọn với độ xiên lớn sẽ tạo độ sâu phần cổ và gương mặt người mặc. Không như những mẫu một hàng khuy, điểm cuối hai ve vest 2 khuy được cố định tại phần eo. Ta sẽ chỉ nhìn thấy toàn bộ của một bên ve áo. Cho nên chỉ kiểu ve nhọn mới đáp ứng được yêu cầu về diện tích, độ phẳng, giúp phần ngực của quý ông được tôn lên. Phần ngực áo sẽ thường được thiết kế với hai khuy giả, cho nên việc dùng ve nhọn là để nhằm tạo sự đối xứng phần mép ngoài ve áo. Kiểu dệt Twill là cách dệt sử dụng lần lượt 2 sợi vải ngang nằm dưới và sau đó là nằm trên 2 sợi vải dọc tạo nên một bề mặt các đường vân chéo đặc biệt. Loại vải vân chéo này dày và mềm mại, có khả năng chống nhăn khá tốt và dễ dàng là ủi. Giày phù hợp: Nâu nhạt/Đỏ burgundy/Đen Sơ mi phù hợp: Sơ mi trắng/đen/đỏ burgundy/Beige... Hoạ tiết Herringbone giúp tạo ra điểm nhấn cho bộ suits, khiến cho người mặc cảm thấy độ sâu hơn, bắt mắt hơn,  Đây cũng là yếu tố giúp cân bằng lại các chi tiết của tổng thể, cũng như là sự cân bằng cổ điển và hiện đại, mang tới vẻ đẹp tinh tế và ấn tượng nhất. Chất liệu vải được sử dụng 80% cotton và 20% poly giúp bộ Suit thoáng mát, thấm hút tốt và vẫn giữ phom, hạn chế nhăn nhàu.', 1],
            /* 56-65 */
        ];

        foreach($products as $product) {
            product::create([
                'name' => $product[0],
                'price' => $product[1],
                'image' => $product[2],
                'category_id' => $product[3],
                'discount_id' => $product[4],
                'quantity' => $product[5],
                'status' => $product[6],
                'featured' => $product[7],
                'address' => $product[8],
                'description' => $product[9],
                'active' => $product[10]
            ]);
        }
    }
}
